apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kuberstack-monitoring-http
  namespace: kube-system
  labels:
    k8s-app: kuberstack-monitoring-http
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  selector:
    matchLabels:
      k8s-app: kuberstack-monitoring-http
  template:
    metadata:
      labels:
        k8s-app: kuberstack-monitoring-http
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      containers:
      - name: kuberstack-monitoring-http
        image: kuberstack/kuberstack-monitoring-http
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
          requests:
            cpu: 100m
            memory: 50Mi
        env:
          - name: CLUSTER_NAME
            value: <cluster-name>
          - name: SLACK_TOKEN
            value: <slack-token>
          - name: SLACK_CHANNEL
            value: <slack-channel>
          - name: UPDATE_INTERVAL
            value: '60'
        volumeMounts:
            - mountPath: /usr/src/app/conf
              name: kuberstack-monitoring-http
              readOnly: true
      volumes:
        - name: kuberstack-monitoring-http
          secret:
            secretName: kuberstack-monitoring-http